server:
  port: 8761

logging:
  file: discovery-service.log

spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: discovery
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery:${server.port}/eureka/

